[package]
name = "prime"
version = "1.0.0"
edition = "2021"

[dependencies]
indicatif = { version = "0.17.8", features = ["rayon"] }
num = "0.4.1"
num-bigint = "0.4.4"
num-iter = "0.1.44"
num-rational = "0.4.2"
rayon = "1.10.0"
